// File name: "Enums.h"
#if ( !defined(ENUMS_H) || defined(GENERATE_ENUM_STRINGS) )

#if (!defined(GENERATE_ENUM_STRINGS))
#define ENUMS_H
#endif

#include "EnumToString.h"

BEGIN_ENUM(EASY_TOKEN_TYPE)
{
	DECL_ENUM_ELEMENT(TOKEN_NONE),
		DECL_ENUM_ELEMENT(INTEGER),
		DECL_ENUM_ELEMENT(DOUBLE),
		DECL_ENUM_ELEMENT(SYMBOL),
		DECL_ENUM_ELEMENT(OPERATOR),
		DECL_ENUM_ELEMENT(TEXT),
		DECL_ENUM_ELEMENT(VARIABLE),
		DECL_ENUM_ELEMENT(KEYWORD)
}
END_ENUM(EASY_TOKEN_TYPE)

BEGIN_ENUM(EASY_OPERATOR_TYPE)
{
	DECL_ENUM_ELEMENT(OPERATOR_NONE),
		DECL_ENUM_ELEMENT(PLUS),
		DECL_ENUM_ELEMENT(MINUS),
		DECL_ENUM_ELEMENT(MULTIPLICATION),
		DECL_ENUM_ELEMENT(DIVISION),
		DECL_ENUM_ELEMENT(EQUAL),
		DECL_ENUM_ELEMENT(NOT_EQUAL),
		DECL_ENUM_ELEMENT(GREATOR),
		DECL_ENUM_ELEMENT(LOWER),
		DECL_ENUM_ELEMENT(GREATOR_EQUAL),
		DECL_ENUM_ELEMENT(LOWER_EQUAL),
		DECL_ENUM_ELEMENT(SINGLE_QUOTES),
		DECL_ENUM_ELEMENT(DOUBLE_QUOTES),
		DECL_ENUM_ELEMENT(LEFT_PARENTHESES),
		DECL_ENUM_ELEMENT(RIGHT_PARENTHESES)
}
END_ENUM(EASY_OPERATOR_TYPE)

BEGIN_ENUM(EASY_KEYWORD_TYPE)
{
	DECL_ENUM_ELEMENT(KEYWORD_NONE),
		DECL_ENUM_ELEMENT(IF),
		DECL_ENUM_ELEMENT(ASSIGNMENT),
		DECL_ENUM_ELEMENT(ELSE),
		DECL_ENUM_ELEMENT(THEN),
		DECL_ENUM_ELEMENT(ASSIGNMENT_SUFFIX),
		DECL_ENUM_ELEMENT(PRINT),
		DECL_ENUM_ELEMENT(OR),
		DECL_ENUM_ELEMENT(AND)
}
END_ENUM(EASY_KEYWORD_TYPE)

#endif 
